# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escolha',
            old_name='nome',
            new_name='item',
        ),
    ]
