# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171016_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escolha',
            name='boolean',
        ),
        migrations.AddField(
            model_name='item',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='quantidate',
            field=models.IntegerField(default=0),
        ),
    ]
